data_path: /home/users/NMED
working_dir: /home/users/eeg_music
group_name: labram_pretrain
seed: 622
cache_dir: ./cache
use_wandb: true

eeg_window_size: 125
eeg_window_stride: 125

embed_dim: 768
patch_size: 25
num_channels: 125
num_heads: 12
num_layers: 12
decoder_embed_dim: 512
decoder_num_heads: 8
decoder_num_layers: 6
mask_ratio: 0.75
dropout: 0.0
use_tokenizer: true
tokenizer_model: vqnsp_encoder_base_decoder_3x200x12
tokenizer_weight: /home/users/eeg_music/results/labram_tokenizer/16-01-2026-13:15:08/best_tokenizer.pth

learning_rate: 1e-4
lr_scheduler: cosine
lr_warmup_steps: 0
max_train_steps: 10000
max_grad_norm: 1.0
validation_steps: 1000
batch_size: 200
val_batch_size: 10
gradient_accumulation_steps: 1
mixed_precision: bf16
save_every_steps: 1000
weight_decay: 0.05

use_augment: true
crop_scale: [0.5, 1.0]
noise_level: 0.01
